app:
  language: ger
  type: live
management:
  endpoints:
    web:
      exposure:
        include: '*'
my:
  app:
    all-sub-props:
      - address: basaksehir
        departments:
          - DE1
          - DE2ğğ
        sub-name: test1
      - address: besiktas
        departments:
          - DE3
          - DE4
        sub-name: test2
    language: eng
    long-description: deneme yapisi
    nick-names:
      - osman
      - osm
      - osmen
      - osoman
      - sdhfghsd
    port: 1000
    sub-props:
      address: atasehir 123
      departments:
        - IT
        - SALE
        - sdbhfwkf
      sub-name: deneme
    sub-props-map:
      abc:
        address: etiler
        departments:
          - IT
          - PPP
        sub-name: test3
server:
  port: 8080
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always
spring:
  application:
    name: spring-training
  profiles:
    default: live
  datasource:
    driverClassName: org.h2.Driver
    password:
    url: jdbc:h2:file:./data/demo
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true